title: Slate-Mod theme
description: Slate-Mod is a modified version of the Slate theme for use on research group websites
lang: en-GB

navbar:
  - link: "index.html"
    text: "Home"
  - link: "research.html"
    text: "Research"
  - link: "publications.html"
    text: "Publications"
